[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx", "nodejs", "npm"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "composer --working-dir=lib/pkp install --no-dev --optimize-autoloader --no-interaction",
    "composer --working-dir=plugins/generic/citationStyleLanguage install --no-dev --optimize-autoloader --no-interaction",
    "composer --working-dir=plugins/paymethod/paypal install --no-dev --optimize-autoloader --no-interaction",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "mkdir -p storage/tmp storage/logs storage/review public",
    "mkdir -p /var/lib/php/session /var/lib/php/wsdlcache",
    "chmod -R 755 storage cache public /var/lib/php"
]

[start]
cmd = "sh /var/www/html/start.sh"
